name: Publish release (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        type: string
        required: true

jobs:
  publish:
    name: Publish release
    uses: ./.github/workflows/shared-publish-release.yml
    permissions:
      contents: write
      discussions: write
      id-token: write
    with:
      tag: ${{ inputs.tag }}
