name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    uses: ./.github/workflows/shared-publish-release.yml
    permissions:
      contents: write
      discussions: write
    with:
      tag: ${{ github.ref_name }}
