name: Publish release (shared)

on:
  workflow_call:
    inputs:
      tag:
        description: The tag to publish the release from
        required: true
        type: string

permissions:
  contents: write
  discussions: write
  id-token: write

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    concurrency: publish-release

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v6
        with:
          makeLatest: never
          reactions: hooray,heart,rocket

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Set SAM template version
        run: |
          VERSION="${{ inputs.tag }}"
          sed -i "s/SemanticVersion: .*/SemanticVersion: ${VERSION#v}/" dist/aws-lambda/template.yaml

      - name: Publish to AWS SAR
        run: |
          sam build --template-file dist/aws-lambda/template.yaml
          sam package \
            --template-file .aws-sam/build/template.yaml \
            --output-template-file packaged.yaml \
            --s3-bucket "${{ vars.AWS_SAR_BUCKET }}"
          sam publish --template packaged.yaml --region us-east-1
